import type { Metadata } from "next";
import { SiteHeader } from "@/components/SiteHeader";
import { PRIVACY_CONTACT_EMAIL, SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: "ShopAI Privacy Policy",
  description:
    "ShopAI Privacy Policy explaining how Facebook/Meta interaction data and related information are collected, used, processed, and protected.",
};

const LAST_UPDATED = "August 13, 2026";

const sections = [
  { id: "introduction", title: "Introduction" },
  { id: "information-we-collect", title: "Information We Collect" },
  { id: "facebook-meta-data", title: "Facebook/Meta Data" },
  { id: "how-we-use-information", title: "How We Use Information" },
  { id: "ai-processing", title: "AI Processing" },
  { id: "data-storage-and-retention", title: "Data Storage and Retention" },
  { id: "third-party-services", title: "Third-Party Services" },
  { id: "data-security", title: "Data Security" },
  { id: "data-sharing", title: "Data Sharing" },
  { id: "user-rights-and-data-deletion", title: "User Rights and Data Deletion" },
  { id: "childrens-privacy", title: "Children's Privacy" },
  { id: "changes", title: "Changes to This Privacy Policy" },
  { id: "contact", title: "Contact Information" },
] as const;

export default function PrivacyPolicyPage() {
  return (
    <>
      <SiteHeader currentPath="/privacy-policy" />
      <main id="main-content" className="site-main">
        <article className="page policy" aria-labelledby="privacy-policy-title">
          <header className="policy__header">
            <h1 id="privacy-policy-title">ShopAI Privacy Policy</h1>
            <p className="policy__updated">
              <time dateTime="2026-08-13">Last Updated: {LAST_UPDATED}</time>
            </p>
          </header>

          <nav className="policy__toc" aria-label="Privacy Policy contents">
            <h2>Contents</h2>
            <ol>
              {sections.map((section) => (
                <li key={section.id}>
                  <a href={`#${section.id}`}>{section.title}</a>
                </li>
              ))}
            </ol>
          </nav>

          <section id="introduction" aria-labelledby="introduction-heading">
            <h2 id="introduction-heading">Introduction</h2>
            <p>
              This Privacy Policy describes how {SITE_NAME} (&quot;we,&quot;
              &quot;us,&quot; or &quot;our&quot;) collects, uses, processes, and
              protects information in connection with our AI-powered lead
              qualification and customer engagement automation project.
            </p>
            <p>
              {SITE_NAME} integrates with Facebook/Meta and uses n8n as an
              automation workflow platform. When people interact with a Facebook
              Page connected to {SITE_NAME}—for example by commenting on
              posts—related interaction data may be received and processed to
              help qualify potential leads and support automated customer
              responses.
            </p>
            <p>
              {SITE_NAME} is currently operated as a learning and development
              project. This Privacy Policy is intended to explain our practices
              clearly and accurately. By interacting with a Facebook Page or
              related services connected to {SITE_NAME}, you acknowledge the
              practices described here.
            </p>
          </section>

          <section
            id="information-we-collect"
            aria-labelledby="information-we-collect-heading"
          >
            <h2 id="information-we-collect-heading">Information We Collect</h2>
            <p>
              Depending on how {SITE_NAME} is configured and how users interact
              with connected Facebook Pages, we may collect or receive the
              following categories of information:
            </p>
            <ul>
              <li>
                Facebook Page interaction data, such as comments on posts and
                related metadata associated with those interactions.
              </li>
              <li>
                Publicly available information associated with those
                interactions, such as a public Facebook profile name, profile
                identifier, or other information made available through Meta
                APIs for the connected Page.
              </li>
              <li>
                Content of messages or comments submitted by users when
                interacting with a connected Facebook Page, to the extent such
                content is provided through Meta&apos;s platform and received by{" "}
                {SITE_NAME}.
              </li>
              <li>
                Technical and operational data generated by our automation
                workflows (for example, timestamps, processing status, and
                workflow identifiers) needed to run and monitor the application.
              </li>
            </ul>
            <p>
              We do not intentionally collect sensitive personal information
              beyond what users choose to share publicly in their Facebook Page
              interactions or what Meta provides through authorized API access
              for the connected Page.
            </p>
          </section>

          <section
            id="facebook-meta-data"
            aria-labelledby="facebook-meta-data-heading"
          >
            <h2 id="facebook-meta-data-heading">Facebook/Meta Data</h2>
            <p>
              {SITE_NAME} may receive and process Facebook Page interaction data
              through Meta&apos;s developer platform and related APIs. This may
              include comments on posts and publicly available information
              associated with those interactions.
            </p>
            <p>
              Access to such data depends on the permissions granted to the
              Meta Developer App connected to {SITE_NAME} and on Meta&apos;s
              platform policies. We use Facebook/Meta data only for the purposes
              described in this Privacy Policy, including lead qualification and
              automated customer engagement related to the connected Page.
            </p>
            <p>
              Your use of Facebook/Meta products is also governed by Meta&apos;s
              own terms and privacy policies. {SITE_NAME} does not control
              Meta&apos;s independent data practices.
            </p>
          </section>

          <section
            id="how-we-use-information"
            aria-labelledby="how-we-use-information-heading"
          >
            <h2 id="how-we-use-information-heading">How We Use Information</h2>
            <p>We use the information described above to:</p>
            <ul>
              <li>
                Receive and process Facebook Page interactions relevant to the
                connected Page.
              </li>
              <li>
                Classify and qualify potential leads based on interaction
                content and related context.
              </li>
              <li>
                Support automated customer engagement and responses through
                configured workflows.
              </li>
              <li>
                Operate, monitor, debug, and improve {SITE_NAME}&apos;s
                automation and AI-assisted features.
              </li>
              <li>
                Comply with applicable legal obligations and respond to valid
                requests related to privacy or data management.
              </li>
            </ul>
            <p>
              <strong>
                {SITE_NAME} does not sell users&apos; personal information.
              </strong>
            </p>
          </section>

          <section id="ai-processing" aria-labelledby="ai-processing-heading">
            <h2 id="ai-processing-heading">AI Processing</h2>
            <p>
              Interaction data received by {SITE_NAME} may be processed by an AI
              agent to classify or qualify potential leads and to support
              automated customer responses. This processing is performed to help
              understand the nature of a comment or interaction and to assist
              with follow-up actions configured in our automation workflows.
            </p>
            <p>
              AI-generated classifications or suggested responses are used to
              support the application&apos;s intended functionality. Outputs may
              be imperfect, and the application may be adjusted or reviewed as
              part of ongoing development.
            </p>
          </section>

          <section
            id="data-storage-and-retention"
            aria-labelledby="data-storage-and-retention-heading"
          >
            <h2 id="data-storage-and-retention-heading">
              Data Storage and Retention
            </h2>
            <p>
              Data processed by {SITE_NAME} may be stored or handled through the
              systems and workflows used to operate the application, including
              automation steps configured in n8n and any related storage
              destinations set up by the application owner.
            </p>
            <p>
              We do not currently maintain a fixed, publicly stated retention
              period for all categories of data. Information is retained only as
              necessary for the application&apos;s intended functionality, for
              operational and development purposes, or as otherwise configured
              by the application owner. When data is no longer needed for these
              purposes, it may be deleted or de-identified according to the
              application&apos;s configuration and available tools.
            </p>
          </section>

          <section
            id="third-party-services"
            aria-labelledby="third-party-services-heading"
          >
            <h2 id="third-party-services-heading">Third-Party Services</h2>
            <p>
              {SITE_NAME} relies on third-party services to operate. These
              currently include:
            </p>
            <ul>
              <li>
                <strong>Meta / Facebook:</strong> Used to connect to Facebook
                Pages and receive interaction data (such as comments and related
                publicly available information) through Meta&apos;s platform and
                APIs. Meta&apos;s handling of data is governed by Meta&apos;s
                own policies.
              </li>
              <li>
                <strong>n8n:</strong> Used as the automation workflow platform
                that may receive, route, transform, and process data as part of{" "}
                {SITE_NAME}&apos;s lead qualification and customer engagement
                workflows. Data handled in n8n is subject to the workflow
                configuration and n8n&apos;s applicable terms and privacy
                practices for the deployment in use.
              </li>
            </ul>
            <p>
              These third parties may process data according to their own terms
              and privacy policies. We encourage you to review those policies for
              more information about their practices.
            </p>
          </section>

          <section id="data-security" aria-labelledby="data-security-heading">
            <h2 id="data-security-heading">Data Security</h2>
            <p>
              We take reasonable measures designed to protect information
              processed by {SITE_NAME} against unauthorized access, alteration,
              disclosure, or destruction. These measures may include access
              controls, secure transmission where supported by underlying
              platforms, and careful configuration of automation workflows.
            </p>
            <p>
              No method of electronic storage or transmission is completely
              secure. While we work to protect information, we cannot guarantee
              absolute security. As a learning and development project, security
              practices may continue to evolve.
            </p>
          </section>

          <section id="data-sharing" aria-labelledby="data-sharing-heading">
            <h2 id="data-sharing-heading">Data Sharing</h2>
            <p>
              We do not sell personal information. We may share or disclose
              information only in the following limited circumstances:
            </p>
            <ul>
              <li>
                With service providers and platforms that help operate{" "}
                {SITE_NAME}, including Meta/Facebook and n8n, as needed to
                provide the application&apos;s functionality.
              </li>
              <li>
                When required by law, regulation, legal process, or governmental
                request.
              </li>
              <li>
                To protect the rights, safety, or integrity of {SITE_NAME}, our
                users, or others, where we believe disclosure is reasonably
                necessary.
              </li>
              <li>
                In connection with a reorganization, transfer, or similar change
                related to the project, subject to appropriate safeguards where
                applicable.
              </li>
            </ul>
          </section>

          <section
            id="user-rights-and-data-deletion"
            aria-labelledby="user-rights-and-data-deletion-heading"
          >
            <h2 id="user-rights-and-data-deletion-heading">
              User Rights and Data Deletion
            </h2>
            <p>
              Depending on applicable law and the nature of your interaction
              with {SITE_NAME}, you may have rights to request access to,
              correction of, or deletion of personal information associated with
              you that we process.
            </p>
            <p>
              <strong>How to request deletion of your data:</strong>
            </p>
            <ol>
              <li>
                Send an email to{" "}
                <a href={`mailto:${PRIVACY_CONTACT_EMAIL}`}>
                  {PRIVACY_CONTACT_EMAIL}
                </a>{" "}
                with the subject line &quot;Data Deletion Request.&quot;
              </li>
              <li>
                Include enough information for us to locate relevant records
                where reasonably possible (for example, the Facebook Page
                involved, approximate date of the interaction, and the public
                name or other identifier associated with your comment or
                interaction).
              </li>
              <li>
                We will review your request and, where applicable, delete or
                de-identify personal information associated with your
                interactions that we control, subject to any legal or
                operational limitations.
              </li>
            </ol>
            <p>
              Please note that information you post publicly on Facebook may
              also remain on Meta&apos;s platform according to Meta&apos;s
              policies and your Facebook account settings. Requests related to
              data held solely by Meta should be directed to Meta through the
              tools and processes Meta provides.
            </p>
          </section>

          <section
            id="childrens-privacy"
            aria-labelledby="childrens-privacy-heading"
          >
            <h2 id="childrens-privacy-heading">Children&apos;s Privacy</h2>
            <p>
              {SITE_NAME} is not directed to children under the age of 13, and
              we do not knowingly collect personal information from children
              under 13. If you believe that a child under 13 has provided
              personal information to us through a connected Facebook Page
              interaction, please contact us using the details below so we can
              take appropriate steps to delete the information where applicable.
            </p>
          </section>

          <section id="changes" aria-labelledby="changes-heading">
            <h2 id="changes-heading">Changes to This Privacy Policy</h2>
            <p>
              We may update this Privacy Policy from time to time to reflect
              changes in our practices, technology, legal requirements, or the
              scope of the {SITE_NAME} project. When we make changes, we will
              update the &quot;Last Updated&quot; date at the top of this page.
            </p>
            <p>
              We encourage you to review this Privacy Policy periodically. Your
              continued interaction with Facebook Pages or services connected to{" "}
              {SITE_NAME} after an update constitutes acknowledgment of the
              revised Privacy Policy, to the extent permitted by applicable law.
            </p>
          </section>

          <section id="contact" aria-labelledby="contact-heading">
            <h2 id="contact-heading">Contact Information</h2>
            <p>
              If you have questions about this Privacy Policy, our data
              practices, or if you wish to submit an access or deletion request,
              please contact us:
            </p>
            <div className="contact-block">
              <p>
                <strong>{SITE_NAME} Privacy Contact</strong>
              </p>
              <p>
                Email:{" "}
                <a href={`mailto:${PRIVACY_CONTACT_EMAIL}`}>
                  {PRIVACY_CONTACT_EMAIL}
                </a>
              </p>
            </div>
          </section>
        </article>
      </main>
    </>
  );
}
